import { BALANCE } from '../config/balance';
import { fmtInt, fmtOne } from './format';

/**
 * Player-facing names and formats for the stats a technology level changes (Work Tree "Current -> Next").
 * Stats not listed here are shown by the level description only.
 */
interface StatLabel { label: string; fmt: (v: number, get: (k: string) => number) => string }

const n1 = (v: number) => (Math.abs(v - Math.round(v)) < 0.05 ? fmtInt(v) : fmtOne(v));
const unit = (u: string) => (v: number) => `${n1(v)} ${u}`;
const pct = (v: number) => `${Math.round(v * 100)} %`;
const perSec = (per: (v: number, g: (k: string) => number) => number) => (v: number, g: (k: string) => number) => `${n1(per(v, g))} /s`;
const onOff = (v: number) => (v >= 1 ? 'Yes' : 'No');
const times = (v: number) => `×${v.toFixed(2)}`;

export const STAT_LABELS: Record<string, StatLabel> = {
  'tool.hands.dig': { label: 'Hay per grab', fmt: n1 },
  'tool.hands.reach': { label: 'Reach', fmt: unit('m') },
  'tool.hands.radius': { label: 'Grab width', fmt: unit('m') },
  'tool.hands.interval': { label: 'Grabs', fmt: (v) => `${fmtOne(1 / v)} /s` },
  'tool.shovel.dig': { label: 'Hay per scoop', fmt: n1 },
  'tool.shovel.radius': { label: 'Blade width', fmt: unit('m') },
  'tool.shovel.interval': { label: 'Swings', fmt: (v) => `${fmtOne(1 / v)} /s` },
  'tool.shovel.reach': { label: 'Reach', fmt: unit('m') },
  'tool.bucket.dig': { label: 'Hay per scoop', fmt: n1 },
  'tool.bucket.carryBonus': { label: 'Extra carry', fmt: (v) => `+${fmtInt(v)}` },
  'tool.bucket.quickDump': { label: 'Quick dump', fmt: onOff },
  'tool.bucket.interval': { label: 'Scoops', fmt: (v) => `${fmtOne(1 / v)} /s` },
  'tool.bucket.dumpRange': { label: 'Dump range', fmt: unit('m') },
  'tool.pitchfork.dig': { label: 'Hay per stab', fmt: n1 },
  'tool.pitchfork.radius': { label: 'Tine width', fmt: unit('m') },
  'tool.pitchfork.interval': { label: 'Stabs', fmt: (v) => `${fmtOne(1 / v)} /s` },
  'tool.pitchfork.reach': { label: 'Reach', fmt: unit('m') },
  'tool.vacuum.rate': { label: 'Suction', fmt: unit('hay/s') },
  'tool.vacuum.reach': { label: 'Reach', fmt: unit('m') },
  'tool.vacuum.radius': { label: 'Cone width', fmt: unit('m') },
  'tool.detector.range': { label: 'Range', fmt: unit('m') },
  'tool.detector.depth': { label: 'Depth', fmt: unit('m') },
  'tool.detector.precision': { label: 'Clean signal', fmt: onOff },
  'tool.detector.directional': { label: 'Direction arrow', fmt: onOff },
  'wheelbarrow.capacity': { label: 'Capacity', fmt: unit('hay') },
  'wheelbarrow.speedMul': { label: 'Push speed', fmt: pct },
  'wheelbarrow.collectRange': { label: 'Collect range', fmt: unit('m') },
  'hopper.capacity': { label: 'Capacity', fmt: unit('hay') },
  'hopper.outputRate': { label: 'Output', fmt: unit('hay/s') },
  'hopper.dualOutput': { label: 'Second output', fmt: onOff },
  'rake.cycleTime': { label: 'Cycle', fmt: unit('s') },
  'rake.push': { label: 'Hay per cycle', fmt: n1 },
  'rake.width': { label: 'Head width', fmt: unit('m') },
  'rake.reach': { label: 'Reach', fmt: unit('m') },
  'rake.trayOutputRate': { label: 'Tray output', fmt: unit('hay/s') },
  'rake.industrial': { label: 'Industrial', fmt: onOff },
  'arm.grab': { label: 'Grab', fmt: unit('hay') },
  'arm.speed': { label: 'Servo speed', fmt: times },
  'arm.rotSpeed': { label: 'Rotation', fmt: unit('°/s') },
  'arm.reach': { label: 'Reach', fmt: unit('m') },
  'arm.smart': { label: 'Smart targeting', fmt: onOff },
  'arm.mk2': { label: 'Advanced model', fmt: onOff },
  'arm.throughputMul': { label: 'Throughput', fmt: times },
  'collector.rate': { label: 'Suction', fmt: unit('hay/s') },
  'collector.radius': { label: 'Radius', fmt: unit('m') },
  'collector.outputRate': { label: 'Output', fmt: unit('hay/s') },
  'collector.buffer': { label: 'Buffer', fmt: unit('hay') },
  'collector.powerMul': { label: 'Power use', fmt: pct },
  'collector.industrial': { label: 'Twin turbine', fmt: onOff },
  'belt.speed': { label: 'Belt throughput', fmt: perSec((v, g) => (v / g('belt.spacing')) * BALANCE.hayPacketSize) },
  'belt.spacing': { label: 'Belt throughput', fmt: perSec((v, g) => (g('belt.speed') / v) * BALANCE.hayPacketSize) },
  'scanner.batch': { label: 'MK1 scan rate', fmt: perSec((v, g) => v / g('scanner.cycle')) },
  'scanner.cycle': { label: 'MK1 scan rate', fmt: perSec((v, g) => g('scanner.batch') / v) },
  'scanner.buffer': { label: 'MK1 buffer', fmt: unit('hay') },
  'scanner.autoEject': { label: 'Auto eject', fmt: onOff },
  'scanner2.speedMul': { label: 'MK2 scan rate', fmt: perSec((v, g) => (g('scanner2.batch') * v) / g('scanner2.cycle')) },
  'scanner2.buffer': { label: 'MK2 buffer', fmt: unit('hay') },
  'scanner2.dualLane': { label: 'MK2 second lane', fmt: onOff },
  'compressor.cycle': { label: 'Press cycle', fmt: unit('s') },
  'compressor.hayPerBale': { label: 'Hay per bale', fmt: n1 },
  'compressor.chambers': { label: 'Chambers', fmt: n1 },
  'compressor.buffer': { label: 'Buffer', fmt: unit('hay') },
  'wrapper.cycle': { label: 'Wrap cycle', fmt: unit('s') },
  'wrapper.premium': { label: 'Premium film', fmt: onOff },
  'econ.wrappedValue': { label: 'Wrapped bale value', fmt: (v) => `$${n1(v)}` },
  'econ.baleValue': { label: 'Bale value', fmt: (v) => `$${n1(v)}` },
  'econ.hayMul': { label: 'Sale value', fmt: times },
  'econ.orderRewardMul': { label: 'Order money', fmt: times },
  'silo.capacity': { label: 'Capacity', fmt: unit('hay') },
  'silo.inputRate': { label: 'Input', fmt: unit('hay/s') },
  'silo.outputRate': { label: 'Output', fmt: unit('hay/s') },
  'silo.dualOutput': { label: 'Second output', fmt: onOff },
  'generator.output': { label: 'Power', fmt: unit('P') },
  'generator.burnRate': { label: 'Fuel at full load', fmt: unit('hay/s') },
  'generator.firebox': { label: 'Firebox', fmt: unit('hay') },
  'generator.industrial': { label: 'Industrial boiler', fmt: onOff },
  'pole.range': { label: 'Range', fmt: unit('m') },
  'pole.connections': { label: 'Machines per pole', fmt: n1 },
  'power.loss': { label: 'Transmission loss', fmt: pct },
  'player.carry': { label: 'Carry', fmt: unit('hay') },
  'player.moveSpeed': { label: 'Walk speed', fmt: unit('m/s') },
};
